config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :images, only: [:create, :update] do
    member do
      post :rotate
    end
  end

  resources :documents do
    member do
      put :handle
      put :request_approval
      put :approve
      put :reject
      put :amend
    end
  end

  resources :categories

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
    get "sign_in", to: "devise/sessions#new"
  end

  root 'documents#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  include Workflow
  belongs_to :currency
  belongs_to :category
  has_many :categories, through: :user
  belongs_to :user
  has_many :currencies, through: :user
  paginates_per 12
  belongs_to :image, dependent: :destroy
  accepts_nested_attributes_for :image
  monetize :amount_subunit, :as => "amount", :allow_nil => true
  before_validation :set_date_to_now
  validates :currency_id, inclusion: { in: ->(document) { document.currency_ids },
    message: "%{value} must be in currencies list" }, allow_nil: true
  validates :category_id, inclusion: { in: ->(document) { document.category_ids },
                                       message: "%{value} must be your category" }, allow_nil: true

  validate do
    self.errors[:date] << "must be a valid date" unless (Date.parse(self.date.to_s) rescue false)
  end

  def set_date_to_now
    if !self.persisted?
      self.date ||= Date.today
    end
  end

  workflow do
    state :new do
      event :handle, transitions_to: :in_process
    end
    state :in_process do
      event :request_approval, transitions_to: :pending_approval
    end
    state :pending_approval do
      event :approve, transitions_to: :ready
      event :reject, transitions_to: :rejected
    end
    state :rejected do
      event :amend, transitions_to: :in_process
    end
    state :ready
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, except: [:index, :new]
  load_and_authorize_resource

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.page params[:page]
  end

# GET /documents/new
  def new
    image = Image.create(user_id: current_user.id)
    @document = image.document
    render 'edit'
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id
    authorize! :create, @document
    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_url}
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def handle
    authorize! :handle, @document
    @document.handle!
    head :ok
  end

  def request_approval
    authorize! :request_approval, @document
    @document.request_approval!
    head :ok
  end

  def approve
    authorize! :approve, @document
    @document.approve!
    head :ok
  end

  def reject
    authorize! :reject, @document
    @document.reject!
    head :ok
  end

  def amend
    authorize! :amend, @document
    @document.amend!
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:date, :amount, :currency_id, :category_id, :description, image_attributes: [:id ,:image] )
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<% content_for :tools do %>
  <%= form_for(@document) do |f| %>

    <% if @document.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>
        <ul>
        <% @document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class ="row">
      <div class="col-sm-10">
        <div class="form-group">
          <%= f.label :date %><br>
          <%= f.text_field :date, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :amount %><br>
          <%= f.text_field :amount, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :currency_id %><br>
          <%= f.collection_select :currency_id, @document.currencies.order(:name), :id, :name, {include_blank: true}, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %><br>
          <%= f.collection_select :category_id, @document.categories.order(:name),:id,:name, {include_blank: true}, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, {class: "form-control"} %>
        </div>
        <div class="form-group">
          <%= f.fields_for :image do |image_form| %>
            <%= image_form.file_field :image, accept: 'image/jpeg,image/gif,image/png', onchange: 'submit_form(this)', id: "image_image", class: "form-control" %>
          <% end %>
        </div>
        <% if can? :update, Document %>
          <div class="actions">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <div class="image-div span12">
      <% if @document.image.present? %>
        <%= image_tag(@document.image.image_url(:medium), class: "img-responsive edit_pic", data: {zoom_image: @document.image.image_url}) %>
      <% end %>
    </div>
    <% if can? :update, Document %>
      <div class="upload-edit">
        <%= button_tag "Change image", onclick: "browse_image()", type: :button, class: :"btn btn-primary" %>
        <p id="notice" class="notice-edit-image"><%= notice %></p>
        <% if @document.image.present? %>
          <div class="rotate-form">
            <%= button_tag "", :class => "btn glyphicon glyphicon-repeat ", id: "rotate_counter_clockwise" %>
            <%= button_tag "", :class => "btn glyphicon glyphicon-repeat", id: "rotate_clockwise" %>
            <%= form_for :image_angle, url: rotate_image_path(:id => @document.image_id),
            remote: true, authenticity_token: true,
            html: {id: "image_angle_form"} do |f| %>
              <%= f.hidden_field :angle, value: "0", id: "angle_field" %>
              <%= f.submit "Save", class: "btn btn-primary" %>
            <%end%>
          </div>
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/_upload_form.html.erb
<% if can? :create, Document %>
  <%= form_for Image.new do |f| %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', onchange: 'submit_form(this)', multiple: true %>
    <%= button_tag "Upload document", type: :button, onclick: "browse_image()", class: :"btn btn-primary btn-upload" %>
  <% end %>
<% end %>

<%= button_to "New document", new_document_path, type: :button, class: "btn btn-primary btn-create", method: :get %>

app/views/documents/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="for-buttons">
      <%= render 'upload_form' %>
    </div>
  </div>
  <div class="col-sm-6">
    <%= paginate @documents %>
  </div>
</div>
<div class="container" id="posts">
  <ul class="row page list-img pagination">
    <% @documents.each do |document| %>
      <li class="col-sm-3 post image">
        <%= link_to image_tag(document.image.image.blank? ? 'Image_upload.png' : document.image.image_url(:small)), edit_document_path(document) %>
        <% if can? :delete, Image %>
          <%= link_to document_path(document), method: :delete, class: "close", data: {confirm: "Are you sure you want to permanently delete this document?"} do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<p id="notice"><%= notice.html_safe if notice %></p>
<div class="for-buttons">
  <%= render 'upload_form' %>
</div>